export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const FETCH_MESSAGE_ERROR = "FETCH_MESSAGE_ERROR";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const SET_MESSAGE_SUCCESS = "SET_MESSAGE_SUCCESS";
export const SET_MESSAGE_ERROR = "SET_MESSAGE_ERROR";
